sudo: required

language: node_js

node_js:
  - "0.10"

before_install:
  - "curl -L https://git.io/ejPSng | /bin/sh"
  - "npm install --save bcrypt"
  - "npm install -g spacejam"
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services: mongodb

script:
- spacejam test --driver-package dispatch:mocha-phantomjs --port 9000 ./