sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L https://raw.githubusercontent.com/boredland/travis-ci-meteor-packages/master/configure.sh | /bin/sh"

env:
  - CXX=g++-4.8

env:
  - TEST_COMMAND=meteor "$@" --full-app --settings settings/settings.json --once --driver-package dispatch:mocha-phantomjs --port 9000

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8